### ISSUE TITLE
Incorrect detection of Chrome-based browser

### ISSUE THREAD

**Issue by 0neGal** [alyssaxuu/motionity#2]
I attempted to checkout Motionity some minutes long ago, and was stopped by an unresponsive page, turns out, `isChrome` detected my browser as Chrome-based even tho it (qutebrowser) is QtWebKit based. Which in turn made it attempt to create an `EyeDropper` which is non-existent in this browser. Causing a reference error.

Instead of checking the user-agent I would advise checking against Chrome exclusive variables/features, i.e the `window.chrome` Object.

Replacing the whole `isChrome` assignment with:

```javascript
var isChrome = (window.chrome && Object.values(window.chrome).length !== 0)
```

It fixes it, returning `false`/`undefined` on none-Chrome browser like QtWebKit browser, but also Firefox based browsers. And returning `true` on Chrome based browsers.

On QtWebKit browsers like qutebrowser, the Object is returned but as an empty Object, whereas on actual Chrome based browsers it returns with values. Firefox or some other browser/engine may however not even have the variable defined, hence the first check on whether the Object even exists.

I would've made a PR but it seems this repo is outdated compared to the site? Not entirely sure.

**Comment by alyssaxuu** [comment]
Ah oops, thank you, just updated it! And yeah the site doesn't use this repo, I might change that though just to make it easier.
